

ACCELERATION = (45) #degrees/sec^2
BASE_VELOCITY = (360 / 8) #degrees per second

BASE_VELOCITY_TRANSMIT_VALUE = 128

MAX_VELOCITY = (256/BASE_VELOCITY_TRANSMIT_VALUE) * 360 / 8 #degrees per second
